# Generated by Django 2.2.5 on 2019-09-17 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion', models.CharField(max_length=100)),
                ('suggestion_text', models.CharField(max_length=500)),
            ],
        ),
    ]
