# Generated by Django 2.2.5 on 2019-09-17 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_suggestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestion',
            old_name='suggestion',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='suggestion',
            old_name='suggestion_text',
            new_name='text',
        ),
    ]
